remote_theme: rundocs/jekyll-rtd-theme
title: Quick Learning Symbol
baseurl: ""
url: "https://learn.symbol-community.com"
languages: ["en", "ja"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
plugins:
  - jekyll-sitemap
  - jekyll-polyglot
